### ISSUE TITLE
Add Desktop-Wallpaper in the Code

### ISSUE THREAD

**Issue by Lima-X-Coding** [tarcisio-marinho/GonnaCry#1]
These are my ways of dealing with such problems
1. Solution:
Add the Picture as an Resource in the Binary and Extracting it in the Process.

2. Solution:
Convert the Picture into C and including it in the solution as an HeaderFile (.h), then using [CreateFile] and [WriteFile] to write the Picture into a Directory.

**Comment by tarcisio-marinho** [comment]
Hey man! I think the second solution can work out, but I dunno how to do it :(
Would appreciate an pull request :)

**Comment by Lima-X-Coding** [comment]
Im just going to explain it how it works.

1. You need something to convert your File to C-Arrays to embed it in the Code (If you can, use HxD).
2. idk if you can use [CreateFile] and [WriteFile] because they are Windows Functions and requier <Windows.h> (so you might need to find something else)

Small Example:
[CreatFile-WriteFile.txt](https://github.com/tarcisio-marinho/GonnaCry/files/1698948/CreatFile-WriteFile.txt)
I Hope i could help you.

**Comment by violennz** [comment]
Escalação de priv
