### ISSUE TITLE
GonnaCry Older Version C Issue [warning: assignment makes integer from pointer without a cast ]

### ISSUE THREAD

**Issue by LearnerNP** [tarcisio-marinho/GonnaCry#6]
I am trying to compile C (Older version) version of GonnaCry but I am running into a problem. I understand this is an older version but would like to request for your help. 

<pre><b>lib/struct.c:</b> In function ‘<b>destroy</b>’:
<b>lib/struct.c:61:27:</b> <font color="#AD7FA8"><b>warning: </b></font>assignment makes integer from pointer without a cast [<font color="#AD7FA8"><b>-Wint-conversion</b></font>]
             *aux-&gt;info[i] <font color="#AD7FA8"><b>=</b></font> &quot;random_string&quot;;
                           <font color="#AD7FA8"><b>^</b></font>
gcc -c lib/func.c -o lib/func.o
gcc lib/gonnacry.o lib/crypto.o lib/struct.o lib/func.o -o bin/gonnacry -lcrypto  </pre>

**Comment by tarcisio-marinho** [comment]
Even with the warning, the code compiles and binaries are stored inside the bin/ directory  !
